### ISSUE TITLE
Memory/Cpu Share Scheduling

### ISSUE THREAD

**Issue by sstarcher** [growbrosops/containership#1]
You mention scheduling based off of tags and constraints.  Do you by chance take memory/cpu shares into account?

**Comment by normanjoyner** [comment]
When [containership.scheduler](https://github.com/growbrosops/containership.scheduler) is finding an available host to run a container, it ensures the host has enough resources to run that container (so it does not oversubscribe). We do not currently have a scheduling strategy that would allow containers to be placed on the least utilized or most utilized host first. The current strategy is to choose a random host from the pool of matching hosts (based on resources, tags, and constraints).

I am certainly open to providing multiple scheduling strategies if that is a desired feature.

**Comment by sstarcher** [comment]
Nope that is sufficient for my needs for now.  I just did not see it in the current version of your docs.  Thanks
