### ISSUE TITLE
Invalid plugin path provided..

### ISSUE THREAD

**Issue by joshpurvis** [growbrosops/containership#2]
Hey guys, I was trying to setup containership, and ran into some issues:

I ran these commands on the first leader (using cloud-init, so it ran as root.. this an issue with npm?):

    # install docker
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
    sh -c 'echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list'
    apt-get update
    apt-get install -y lxc-docker
    gpasswd -a ubuntu docker

    # install nodejs
    apt-get update
    apt-get install curl build-essential make gcc g++ -y
    curl -sL https://deb.nodesource.com/setup | sudo bash -
    apt-get install nodejs -y

Ran as ubuntu user

    sudo npm install containership -g

I get a warning when installing containership:

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/ubuntu/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/containership/node_modules/containership.core/node_modules/praetor/node_modules/legiond/node_modu
les/node-aes-gcm/.node-gyp"
```

Ignoring this, I then tried this chain of commands:

    $ containership agent --mode leader --cidr 10.0.0.0/24
    Invalid plugin path provided!

    $ containership plugin add service-discovery
    $ containership plugin add navigator

    $ containership agent --mode leader --cidr 10.0.0.0/24
    Failed to load containership.plugin.navigator plugin
    Failed to load containership.plugin.service-discovery plugin

I then circled back on that gyp warning. Found this: https://github.com/TooTallNate/node-gyp/issues/454 .. Tried on a clean instance with the `--unsafe-perm` workaround in that issue, but got the same results. 

I'm relatively new to nodejs, especially how npm deals with permissions. Am I missing something or doing something naive?

**Comment by joshpurvis** [comment]
Just tried without cloud-init on a clean instance, so all commands were ran manually by ubuntu user -- same result.

**Comment by phildougherty** [comment]
What version of node are you using @joshpurvis?

**Comment by joshpurvis** [comment]
I tore down those instances and I'm at home now, but I was able to reproduce it here on my local box (also ubuntu 14.04).

     » node --version                                                                                                       
    v0.10.25
     » docker --version                                                                                                     
    Docker version 1.5.0, build a8a31ef
     » containership --version                                                                                              
    Invalid plugin path provided!
    v0.1.3

I can't be for certain, but I swear I got further over the weekend, prior to updating containership on this box. So I suspect it might be related to the latest version.

**Comment by normanjoyner** [comment]
@joshpurvis if the npm install succeeds, I think these warnings can safely be ignored. I assume it is completed successfully as you were able to use the `containership` executable.

I am looking into the plugin issue now. It could certainly be related to the latest release.

**Comment by normanjoyner** [comment]
@joshpurvis, version `0.1.4` should fix this issue. CLI plugin support was added in `0.1.3` and did not properly check if the default plugins directory existed.

**Comment by joshpurvis** [comment]
That definitely clears up the invalid plugin path error. I'll try spinning up a cluster tomorrow morning. Thanks!
